// Auth
export const LOGIN_SAGA = "LOGIN_SAGA";
export const CHECK_LOGIN_SAGA = "CHECK_LOGIN_SAGA";
export const LOGOUT_SAGA = "LOGOUT_SAGA";
export const REGISTER_SAGA = "REGISTER_SAGA";

// Admin
export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";
export const GET_QUANTITY_SAGA = "GET_QUANTITY_SAGA";
export const GET_SMARTPHONE_SAGA = "GET_SMARTPHONE_SAGA";
export const GET_TABLET_SAGA = "GET_TABLET_SAGA";
export const GET_LAPTOP_SAGA = "GET_LAPTOP_SAGA";
export const GET_ACCESSORY_SAGA = "GET_ACCESSORY_SAGA";
export const GET_SWATCH_SAGA = "GET_SWATCH_SAGA";
export const GET_PC_SAGA = "GET_PC_SAGA";

export const ADD_SMARTPHONE_SAGA = "ADD_SMARTPHONE_SAGA";
export const ADD_TABLET_SAGA = "ADD_TABLET_SAGA";
export const ADD_LAPTOP_SAGA = "ADD_LAPTOP_SAGA";
export const ADD_ACCESSORY_SAGA = "ADD_ACCESSORY_SAGA";
export const ADD_SWATCH_SAGA = "ADD_SWATCH_SAGA";
export const ADD_PC_SAGA = "ADD_PC_SAGA";

export const DELETE_SMARTPHONE_SAGA = "DELETE_SMARTPHONE_SAGA";
export const DELETE_LAPTOP_SAGA = "DELETE_LAPTOP_SAGA";
export const DELETE_TABLET_SAGA = "DELETE_TABLET_SAGA";
export const DELETE_ACCESSORY_SAGA = "DELETE_ACCESSORY_SAGA";
export const DELETE_SWATCH_SAGA = "DELETE_SWATCH_SAGA";
export const DELETE_PC_SAGA = "DELETE_PC_SAGA";

export const EDIT_SMARTPHONE_SAGA = "EDIT_SMARTPHONE_SAGA";
export const EDIT_LAPTOP_SAGA = "EDIT_LAPTOP_SAGA";
export const EDIT_TABLET_SAGA = "EDIT_TABLET_SAGA";
export const EDIT_ACCESSORY_SAGA = "EDIT_ACCESSORY_SAGA";
export const EDIT_SWATCH_SAGA = "EDIT_SWATCH_SAGA";
export const EDIT_PC_SAGA = "EDIT_PC_SAGA";

// SEARCH
export const SEARCH_SMARTPHONE_SAGA = "SEARCH_SMARTPHONE_SAGA";
export const SEARCH_LAPTOP_SAGA = "SEARCH_LAPTOP_SAGA";
export const SEARCH_TABLET_SAGA = "SEARCH_TABLET_SAGA";
export const SEARCH_ACCESSORY_SAGA = "SEARCH_ACCESSORY_SAGA";
export const SEARCH_SWATCH_SAGA = "SEARCH_SWATCH_SAGA";
export const SEARCH_PC_SAGA = "SEARCH_PC_SAGA";
export const SEARCH_PRODUCT_SAGA = "SEARCH_PRODUCT_SAGA";

// SEARCH RECOMMEND
export const SEARCH_RECOMMEND_PRODUCT_SAGA = "SEARCH_RECOMMEND_PRODUCT_SAGA";

// HOME PAGE
export const GET_DATA_HOME_PAGE_SAGA = "GET_DATA_HOME_PAGE_SAGA";
export const ADD_NEW_HOME_PAGE_SAGA = "ADD_NEW_HOME_PAGE_SAGA";
export const EDIT_HOME_PAGE_SAGA = "EDIT_HOME_PAGE_SAGA";

// SMARTPHONE PAGE
export const GET_DATA_SMARTPHONE_PAGE_SAGA = "GET_DATA_SMARTPHONE_PAGE_SAGA";
export const ADD_NEW_SMARTPHONE_PAGE_SAGA = "ADD_NEW_SMARTPHONE_PAGE_SAGA";
export const EDIT_SMARTPHONE_PAGE_SAGA = "EDIT_NEW_SMARTPHONE_PAGE_SAGA";

// LAPTOP PAGE
export const GET_DATA_LAPTOP_PAGE_SAGA = "GET_DATA_LAPTOP_PAGE_SAGA";
export const ADD_NEW_LAPTOP_PAGE_SAGA = "ADD_NEW_LAPTOP_PAGE_SAGA";
export const EDIT_LAPTOP_PAGE_SAGA = "EDIT_LAPTOP_PAGE_SAGA";

// TABLET PAGE
export const GET_DATA_TABLET_PAGE_SAGA = "GET_DATA_TABLET_PAGE_SAGA";
export const ADD_NEW_TABLET_PAGE_SAGA = "ADD_NEW_TABLET_PAGE_SAGA";
export const EDIT_TABLET_PAGE_SAGA = "EDIT_TABLET_PAGE_SAGA";

// ACCESSORY PAGE
export const GET_DATA_ACCESSORY_PAGE_SAGA = "GET_DATA_ACCESSORY_PAGE_SAGA";
export const ADD_NEW_ACCESSORY_PAGE_SAGA = "ADD_NEW_ACCESSORY_PAGE_SAGA";
export const EDIT_ACCESSORY_PAGE_SAGA = "EDIT_ACCESSORY_PAGE_SAGA";

// SWATCH PAGE
export const GET_DATA_SWATCH_PAGE_SAGA = "GET_DATA_SWATCH_PAGE_SAGA";
export const ADD_NEW_SWATCH_PAGE_SAGA = "ADD_NEW_SWATCH_PAGE_SAGA";
export const EDIT_SWATCH_PAGE_SAGA = "EDIT_SWATCH_PAGE_SAGA";

// PC PAGE
export const GET_DATA_PC_PAGE_SAGA = "GET_DATA_PC_PAGE_SAGA";
export const ADD_NEW_PC_PAGE_SAGA = "ADD_NEW_PC_PAGE_SAGA";
export const EDIT_PC_PAGE_SAGA = "EDIT_PC_PAGE_SAGA";

// GET DETAIL
export const GET_DETAIL_PRODUCT_SAGA = "GET_DETAIL_PRODUCT_SAGA";

// FILTER
export const FILTER_PRODUCT_SAGA = "FILTER_PRODUCT_SAGA";

// COMMENT
export const GET_COMMENT_SAGA = "GET_COMMENT_SAGA";
export const CREATE_COMMENT_SAGA = "CREATE_COMMENT_SAGA";
export const EDIT_COMMENT_SAGA = "EDIT_COMMENT_SAGA";
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";

// CART
export const GET_CART_SAGA = "GET_CART_SAGA";
export const ADD_TO_CART_SAGA = "ADD_TO_CART_SAGA";
export const EDIT_CART_SAGA = "EDIT_CART_SAGA";
export const DELETE_CART_SAGA = "DELETE_CART_SAGA";
export const DELETE_ALL_CART_SAGA = "DELETE_ALL_CART_SAGA";

// HISTORY
export const GET_HISTORY_SAGA = "GET_HISTORY_SAGA";
export const ADD_HISTORY_SAGA = "ADD_HISTORY_SAGA";
export const EDIT_HISTORY_SAGA = "EDIT_HISTORY_SAGA";
export const DELETE_HISTORY_SAGA = "DELETE_HISTORY_SAGA";
export const GET_ALL_HISTORY_SAGA = "GET_ALL_HISTORY_SAGA";
export const GET_ALL_HISTORY_SIGN_SAGA = "GET_ALL_HISTORY_SIGN_SAGA";
export const GET_ALL_HISTORY_NO_SIGN_SAGA = "GET_ALL_HISTORY_NO_SIGN_SAGA";
export const SIGN_HISTORY_SAGA = "SIGN_HISTORY_SAGA";
