export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const SET_LOADING_SKELETON = "SET_LOADING_SKELETON";
export const HIDE_LOADING_SKELETON = "HIDE_LOADING_SKELETON";

export const ADD_NAVIGATE = "ADD_NAVIGATE";

export const SET_USER = "SET_USER";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const CHECK_LOGIN = "CHECK_LOGIN";

export const SET_ALL_USER = "SET_ALL_USER";
export const SEARCH_USER = "SEARCH_USER";

export const SET_QUANTITY = "SET_QUANTITY";
export const SET_SMARTPHONE = "SET_SMARTPHONE";
export const SET_TABLET = "SET_TABLET";
export const SET_ACCESSORY = "SET_ACCESSORY";
export const SET_SWATCH = "SET_SWATCH";
export const SET_PC = "SET_PC";
export const SET_LAPTOP = "SET_LAPTOP";

export const HIDE_CARD_PRODUCT = "HIDE_CARD_PRODUCT";
export const OPEN_MODAL_HOC = "OPEN_MODAL_HOC";

export const OPEN_DRAWER_HOC = "OPEN_DRAWER";
export const HIDE_DRAWER_HOC = "HIDE_DRAWER";

export const SET_SMARTPHONE_EDIT = "SET_SMARTPHONE_EDIT";
export const SET_RECOMMEND_PRODUCT = "SET_RECOMMEND_PRODUCT";

export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";

export const SET_DATA_HOME_PAGE = "SET_DATA_HOME_PAGE";
export const SET_DATA_SMARTPHONE_PAGE = "SET_DATA_SMARTPHONE_PAGE";

export const SET_PRODUCT_CHOOSE = "SET_PRODUCT_CHOOSE";
export const SET_DATA_LAPTOP_PAGE = "SET_DATA_LAPTOP_PAGE";
export const SET_DATA_TABLET_PAGE = "SET_DATA_TABLET_PAGE";
export const SET_DATA_ACCESSORY_PAGE = "SET_DATA_ACCESSORY_PAGE";
export const SET_DATA_SWATCH_PAGE = "SET_DATA_SWATCH_PAGE";
export const SET_DATA_PC_PAGE = "SET_DATA_PC_PAGE";

export const HANDLE_SEARCH_PRODUCT_RECOMMEND =
  "HANDLE_SEARCH_PRODUCT_RECOMMEND";
export const SET_PRODUCT_SEARCH = "SET_PRODUCT_SEARCH";

export const SET_FILTER_PRODUCT = "SET_FILTER_PRODUCT";
export const SET_CURRENT_TOTAL_PRODUCT = "SET_CURRENT_TOTAL_PRODUCT";
export const SET_COMMENT = "SET_COMMENT";

export const SET_SHOPPING_CART = "SET_SHOPPING_CART";

export const SHOW_LOADING_HISTORY = "SHOW_LOADING_HISTORY";
export const HIDE_LOADING_HISTORY = "HIDE_LOADING_HISTORY";

export const SHOW_LOADING_SHOPPING_CART = "SHOW_LOADING_SHOPPING_CART";
export const HIDE_LOADING_SHOPPING_CART = "HIDE_LOADING_SHOPPING_CART";

export const SET_HISTORY = "SET_HISTORY";
export const SET_HISTORY_ADMIN = "SET_HISTORY_ADMIN";
export const SHOW_LOADING_FILTER = "SHOW_LOADING_FILTER";
export const HIDE_LOADING_FILTER = "HIDE_LOADING_FILTER";
